title: Steven Black Consulting
url: http://stevenblack.com
author: "Steven Black"
metakeywords: "Steven Black, Project Manager, Project Turnarounds, Web Developer, Wiki Meister, INTL, INTL Toolkit, Visual FoxPro, Mentoring, Multilingual Application Development,  Project Leadership, Training, Consulting"
metadescription: "Website of Steven Black Consulting"
permalink: /articles/:title/
analytics: UA-212713-3

posts: posts

# images
image_default_alt: Steven Black Consulting

exclude: [ ".git", "Rakefile", ".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less", "_site/font-awesome/docs/" ]

exclude:
  - Rakefile
  - .editorconfig
  - .gitignore
  - .ruby-version
  - bower.json
  - composer.json
  - CONTRIBUTING.md
  - CNAME
  - LICENSE
  - Gruntfile.js
  - package.json
  - README.md
  - less
  - _site/font-awesome/docs/
  - .git
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - any_additional_item # any user-specific lis

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]